# Site settings
title: TeamPtitsJusAllTheTime
description: Les Ptits Jus c'est Tout le Temps !
keywords: Blog, Ptits Jus
author: UneAmatriceDeJus
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ellenhaas.github.io/ptitsjusallthetime/" # the base hostname & protocol for your site
